default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: wikiful_development
  encoding: unicode
  user: wikiful
  host: localhost

test:
  <<: *default
  database: wikiful_test
  user: wikiful
  host: localhost

production:
  <<: *default
  database: wikiful_production
