# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cf4bef1c6269f126546c3c486e0b328ad0872f72a36540950aabf162b629ef899501014e5b710e930c0dd1edeb999c9d84fc3ff1844daaa9644032220805cd1

test:
  secret_key_base: cb171a96ebc0c9de9a9eda93e574a47893ae0a8f59ec0f97418dfdd54280631ca596b64d2de824a4ffbebce4d9fa91e93e99476b4f215ed2ebb8d15a37c8b8e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
